fieldLayouts:
  e25ab42f-df9b-409a-aeef-ed85b9ed8844:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 02d1e75d-fbef-4293-8f08-41b618bb592f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e469fe2a-5e1c-46e2-8631-a1606b344267
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34bd3b6f-3897-43d1-b5ac-46e96103a2bb # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04e83f4-eeb6-4d7b-95e9-bd548a7b000a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04dbcc16-7d8e-4b2c-aa78-819dcf5126e5 # Accordion
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dc0e53e-b6f5-46fc-92ac-a4653568464a
            userCondition: null
            warning: null
            width: 100
        name: Accordions
        uid: e1a30c35-ccc6-4d89-97e9-93dcf45c3afe
        userCondition: null
handle: accordions
hasTitleField: true
name: Accordions
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
