fieldLayouts:
  c082caf5-ada3-46d2-963d-b5090ce5295a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 02d1e75d-fbef-4293-8f08-41b618bb592f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43943a77-bf00-4a79-a502-8352c4bd5c40
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 34bd3b6f-3897-43d1-b5ac-46e96103a2bb # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c15fbe9-2d05-471a-af5e-923d9920014d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70b9b5c3-fff0-4cd3-9d58-d2ea8a6c62b9 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 148c8b20-c297-41ff-b268-5658bd550557
            userCondition: null
            warning: null
            width: 100
        name: Accordion
        uid: 0dd1a02f-524b-4446-bbc4-c108555d558a
        userCondition: null
handle: accordion
hasTitleField: true
name: Accordion
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
