fieldLayouts:
  fd83d8e8-9fa3-4a3c-be77-3ef9028c384e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 913f7782-f162-4899-a94d-6e5cf17692a2 # Strapline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6102476e-7067-4a4e-96d3-cd648e4d1cf1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02d1e75d-fbef-4293-8f08-41b618bb592f # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 480b2bf6-835e-4731-848b-cc28ec1a04d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 70b9b5c3-fff0-4cd3-9d58-d2ea8a6c62b9 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 432d0a1c-721e-4f13-80c3-cc695dd166cb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1fac2f0f-2a5b-42c5-9ec8-9884aa24ae3c # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82466393-8fc6-4615-96ea-bf39f554982a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c5b991cd-57b8-4853-82a9-8db21b3baca7
        userCondition: null
handle: welcomeHero
hasTitleField: true
name: 'Welcome Hero'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
