columnSuffix: null
handle: accordions
instructions: null
name: Accordions
searchable: false
settings:
  entryTypes:
    - 0d16cec4-9156-4ffa-8ed4-373afacadc5d # Accordions
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
