columnSuffix: null
handle: accordion
instructions: null
name: Accordion
searchable: false
settings:
  entryTypes:
    - 9b342512-e9ab-4294-8680-41d455663101 # Accordion
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
