columnSuffix: null
handle: addresses
instructions: null
name: Addresses
searchable: false
settings:
  maxAddresses: null
  minAddresses: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
